// AUTO-GENERATED by scripts/build-real-inventory.ts from the supplier document.
// Real ABB inventory (robots + parts) that nodibot actually stocks. Reviewed by a
// human before import. Regenerate only when the source document changes.
//
// Summary: 65 unique items (24 robots, 41 parts);
// 17 already existed as crawled rows, 48 are new.

export type RealCat = "robots" | "controllers" | "hmi" | "motion" | "mechanical" | "consumables";

export interface RealItem {
  pn: string;                    // canonical part number (unique)
  brand: "ABB";
  name: string;                  // English display name
  cat: RealCat;
  series: string | null;
  equipment_type: string | null;
  qty: number;                   // physical units in hand
  alternative_pns: string[];
  images: string[];              // all docx media filenames, primary first
  primaryImage: string | null;   // first media filename (catalog card)
  docNames: string[];            // original doc line names (traceability)
  existing: boolean;             // already a row in the DB (was crawled/dummy)
  existingImageStatus: string | null;
}

export const REAL_ITEMS: RealItem[] = [
  {
    "pn": "IRB120-3/0.6",
    "brand": "ABB",
    "name": "IRB 120 \u2014 3 kg / 0.6 m",
    "cat": "robots",
    "series": "IRB 120",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image35.jpeg",
    "docNames": [
      "IRB120-3/0.6"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image35.jpeg",
      "image36.jpeg"
    ]
  },
  {
    "pn": "IRB1200-5/0.9",
    "brand": "ABB",
    "name": "IRB 1200 \u2014 5 kg / 0.9 m",
    "cat": "robots",
    "series": "IRB 1200",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image5.jpeg",
    "docNames": [
      "IRB1200-5/0.9"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image5.jpeg",
      "image6.jpeg"
    ]
  },
  {
    "pn": "IRB1200-7/0.7",
    "brand": "ABB",
    "name": "IRB 1200 \u2014 7 kg / 0.7 m",
    "cat": "robots",
    "series": "IRB 1200",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image3.jpeg",
    "docNames": [
      "IRB1200-7/0.7"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image3.jpeg",
      "image4.jpeg"
    ]
  },
  {
    "pn": "IRB14000-0.5/0.5",
    "brand": "ABB",
    "name": "IRB 14000 \u2014 0.5 kg / 0.5 m (YuMi)",
    "cat": "robots",
    "series": "IRB 14000",
    "equipment_type": "dual-arm collaborative robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image49.jpeg",
    "docNames": [
      "IRB14000-0.5/0.5"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image49.jpeg",
      "image50.jpeg"
    ]
  },
  {
    "pn": "IRB1410-5/1.45",
    "brand": "ABB",
    "name": "IRB 1410 \u2014 5 kg / 1.45 m",
    "cat": "robots",
    "series": "IRB 1410",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image31.jpeg",
    "docNames": [
      "IRB1410-5/1.45"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image31.jpeg",
      "image32.jpeg"
    ]
  },
  {
    "pn": "IRB1600-10/1.45",
    "brand": "ABB",
    "name": "IRB 1600 \u2014 10 kg / 1.45 m",
    "cat": "robots",
    "series": "IRB 1600",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image15.jpeg",
    "docNames": [
      "IRB1600-10/1.45"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image15.jpeg",
      "image16.jpeg"
    ]
  },
  {
    "pn": "IRB1600ID-6/1.55",
    "brand": "ABB",
    "name": "IRB 1600ID \u2014 6 kg / 1.55 m",
    "cat": "robots",
    "series": "IRB 1600ID",
    "equipment_type": "6-axis articulated robot (integrated dressing)",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image7.jpeg",
    "docNames": [
      "IRB1600ID-6/1.55"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image7.jpeg",
      "image8.jpeg"
    ]
  },
  {
    "pn": "IRB2400/16",
    "brand": "ABB",
    "name": "IRB 2400/16",
    "cat": "robots",
    "series": "IRB 2400",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image39.jpeg",
    "docNames": [
      "IRB2400/16"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image39.jpeg",
      "image40.jpeg"
    ]
  },
  {
    "pn": "IRB2600-12/1.85",
    "brand": "ABB",
    "name": "IRB 2600 \u2014 12 kg / 1.85 m",
    "cat": "robots",
    "series": "IRB 2600",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image37.jpeg",
    "docNames": [
      "IRB2600-12/1.85"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image37.jpeg",
      "image38.jpeg"
    ]
  },
  {
    "pn": "IRB2600-20/1.65",
    "brand": "ABB",
    "name": "IRB 2600 \u2014 20 kg / 1.65 m",
    "cat": "robots",
    "series": "IRB 2600",
    "equipment_type": "6-axis articulated robot",
    "qty": 2,
    "alternative_pns": [],
    "primaryImage": "image1.jpeg",
    "docNames": [
      "IRB2600-20/1.65",
      "IRB2600-20/1.65"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image1.jpeg",
      "image11.jpeg",
      "image2.jpeg"
    ]
  },
  {
    "pn": "IRB2600ID/8/2.00",
    "brand": "ABB",
    "name": "IRB 2600ID \u2014 8 kg / 2.00 m",
    "cat": "robots",
    "series": "IRB 2600ID",
    "equipment_type": "6-axis articulated robot (integrated dressing)",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image51.jpeg",
    "docNames": [
      "IRB2600ID/8/2.00"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image51.jpeg",
      "image52.jpeg"
    ]
  },
  {
    "pn": "IRB4400/60",
    "brand": "ABB",
    "name": "IRB 4400/60",
    "cat": "robots",
    "series": "IRB 4400",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image29.jpeg",
    "docNames": [
      "IRB4400/60"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image29.jpeg",
      "image30.jpeg"
    ]
  },
  {
    "pn": "IRB4400L-10",
    "brand": "ABB",
    "name": "IRB 4400L",
    "cat": "robots",
    "series": "IRB 4400L",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image41.jpeg",
    "docNames": [
      "IRB4400L-10"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image41.jpeg",
      "image42.jpeg"
    ]
  },
  {
    "pn": "IRB4600-40/2.55",
    "brand": "ABB",
    "name": "IRB 4600 \u2014 40 kg / 2.55 m",
    "cat": "robots",
    "series": "IRB 4600",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image1.jpeg",
    "docNames": [
      "IRB4600-40/2.55"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image1.jpeg",
      "image2.jpeg"
    ]
  },
  {
    "pn": "IRB4600-45/2.05",
    "brand": "ABB",
    "name": "IRB 4600 \u2014 45 kg / 2.05 m",
    "cat": "robots",
    "series": "IRB 4600",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image45.jpeg",
    "docNames": [
      "IRB4600-45/2.05"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image45.jpeg",
      "image46.jpeg"
    ]
  },
  {
    "pn": "IRB4600-60/2.05",
    "brand": "ABB",
    "name": "IRB 4600 \u2014 60 kg / 2.05 m",
    "cat": "robots",
    "series": "IRB 4600",
    "equipment_type": "6-axis articulated robot",
    "qty": 2,
    "alternative_pns": [],
    "primaryImage": "image17.jpeg",
    "docNames": [
      "IRB4600-60/2.05",
      "IRB4600-60/2.05"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image17.jpeg",
      "image19.jpeg",
      "image18.jpeg"
    ]
  },
  {
    "pn": "IRB52",
    "brand": "ABB",
    "name": "IRB 52 Paint Robot",
    "cat": "robots",
    "series": "IRB 52",
    "equipment_type": "paint robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image43.jpeg",
    "docNames": [
      "IRB52"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image43.jpeg",
      "image44.jpeg"
    ]
  },
  {
    "pn": "IRB5510",
    "brand": "ABB",
    "name": "IRB 5510 Paint Robot",
    "cat": "robots",
    "series": "IRB 5510",
    "equipment_type": "paint robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image25.jpeg",
    "docNames": [
      "IRB5510"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image25.jpeg",
      "image26.jpeg"
    ]
  },
  {
    "pn": "IRB660-180/3.15",
    "brand": "ABB",
    "name": "IRB 660 \u2014 180 kg / 3.15 m Palletizer",
    "cat": "robots",
    "series": "IRB 660",
    "equipment_type": "4-axis palletizing robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image13.jpeg",
    "docNames": [
      "IRB660-180/3.15"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image13.jpeg",
      "image14.jpeg"
    ]
  },
  {
    "pn": "IRB6640-130/3.2",
    "brand": "ABB",
    "name": "IRB 6640 \u2014 130 kg / 3.2 m",
    "cat": "robots",
    "series": "IRB 6640",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image33.jpeg",
    "docNames": [
      "IRB6640-130/3.2"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image33.jpeg",
      "image34.jpeg"
    ]
  },
  {
    "pn": "IRB6700-150/3.2",
    "brand": "ABB",
    "name": "IRB 6700 \u2014 150 kg / 3.2 m",
    "cat": "robots",
    "series": "IRB 6700",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image27.jpeg",
    "docNames": [
      "IRB6700-150/3.2"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image27.jpeg",
      "image28.jpeg"
    ]
  },
  {
    "pn": "IRB6700-200/2.60",
    "brand": "ABB",
    "name": "IRB 6700 \u2014 200 kg / 2.60 m",
    "cat": "robots",
    "series": "IRB 6700",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image9.jpeg",
    "docNames": [
      "IRB6700-200/2.60"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image9.jpeg",
      "image10.jpeg"
    ]
  },
  {
    "pn": "IRB6700-235/2.65",
    "brand": "ABB",
    "name": "IRB 6700 \u2014 235 kg / 2.65 m",
    "cat": "robots",
    "series": "IRB 6700",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image21.jpeg",
    "docNames": [
      "IRB6700-235/2.65"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image21.jpeg",
      "image22.jpeg"
    ]
  },
  {
    "pn": "IRB6700-300/2.70",
    "brand": "ABB",
    "name": "IRB 6700 \u2014 300 kg / 2.70 m",
    "cat": "robots",
    "series": "IRB 6700",
    "equipment_type": "6-axis articulated robot",
    "qty": 2,
    "alternative_pns": [],
    "primaryImage": "image23.jpeg",
    "docNames": [
      "IRB6700-300/2.70",
      "IRB6700-300/2.70"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image23.jpeg",
      "image47.jpeg",
      "image24.jpeg"
    ]
  },
  {
    "pn": "3HAC044075-001",
    "brand": "ABB",
    "name": "SMB Battery 7.2V (Li-SOCl2)",
    "cat": "consumables",
    "series": null,
    "equipment_type": "Battery",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image92.jpeg",
    "docNames": [
      "ABB\u7535\u6c603HAC044075-001"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image92.jpeg"
    ]
  },
  {
    "pn": "3HAC16831-1",
    "brand": "ABB",
    "name": "Battery 3HAC16831-1",
    "cat": "consumables",
    "series": null,
    "equipment_type": "Battery",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image87.jpeg",
    "docNames": [
      "ABB\u7535\u6c603HAC16831-1"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image87.jpeg"
    ]
  },
  {
    "pn": "3HAC025097-001",
    "brand": "ABB",
    "name": "Main Computer DSQC639",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Main Computer",
    "qty": 2,
    "alternative_pns": [
      "DSQC639"
    ],
    "primaryImage": "image67.jpeg",
    "docNames": [
      "\u4e3b\u673a3HAC025097-001",
      "\u4e3b\u677fDSQC639"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image67.jpeg",
      "image74.jpeg"
    ]
  },
  {
    "pn": "3HAC025784-001",
    "brand": "ABB",
    "name": "Combi I/O Unit DSQC651 (8DI/8DO/2AO)",
    "cat": "controllers",
    "series": null,
    "equipment_type": "I/O Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC651"
    ],
    "primaryImage": "image65.jpeg",
    "docNames": [
      "IO\u6a21\u5757DSQC651"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image65.jpeg"
    ]
  },
  {
    "pn": "3HAC025917-001",
    "brand": "ABB",
    "name": "I/O Unit DSQC652 (16DI/16DO)",
    "cat": "controllers",
    "series": null,
    "equipment_type": "I/O Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC652"
    ],
    "primaryImage": "image66.jpeg",
    "docNames": [
      "IO\u6a21\u5757DSQC652"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image66.jpeg"
    ]
  },
  {
    "pn": "3HAC026272-001",
    "brand": "ABB",
    "name": "Safety Board 3HAC026272-001",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Safety Board",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image76.jpeg",
    "docNames": [
      "\u5b89\u5168\u677f\u53613HAC026272-001"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image76.jpeg"
    ]
  },
  {
    "pn": "3HAC029157-001",
    "brand": "ABB",
    "name": "Axis Computer DSQC668",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Axis Computer",
    "qty": 2,
    "alternative_pns": [
      "DSQC668"
    ],
    "primaryImage": "image77.jpeg",
    "docNames": [
      "\u8f74\u8ba1\u7b97\u673a\u677f\u5361DSQC668",
      "\u8f74\u8ba1\u7b97\u673a\u677f\u5361DSQC668"
    ],
    "existing": true,
    "existingImageStatus": "missing",
    "images": [
      "image77.jpeg",
      "image85.jpeg",
      "image78.jpeg"
    ]
  },
  {
    "pn": "3HAC031670-001",
    "brand": "ABB",
    "name": "ProfiNet Board DSQC688",
    "cat": "controllers",
    "series": null,
    "equipment_type": "ProfiNet Board",
    "qty": 1,
    "alternative_pns": [
      "DSQC688"
    ],
    "primaryImage": "image73.jpeg",
    "docNames": [
      "Profinet\u677f\u5361DSQC688"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image73.jpeg"
    ]
  },
  {
    "pn": "3HAC037084-001",
    "brand": "ABB",
    "name": "DeviceNet Board DSQC697 (SST-DN4-PCI)",
    "cat": "controllers",
    "series": null,
    "equipment_type": "DeviceNet Board",
    "qty": 1,
    "alternative_pns": [
      "DSQC697"
    ],
    "primaryImage": "image57.jpeg",
    "docNames": [
      "DeviceNet\u677fDSQC697"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image57.jpeg",
      "image58.jpeg"
    ]
  },
  {
    "pn": "3HAC042766-001",
    "brand": "ABB",
    "name": "Main Computer DSQC1000",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Main Computer",
    "qty": 1,
    "alternative_pns": [
      "DSQC1000"
    ],
    "primaryImage": "image75.jpeg",
    "docNames": [
      "ABB\u4e3b\u673aDSQC1000"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image75.jpeg"
    ]
  },
  {
    "pn": "3HAC050363-001",
    "brand": "ABB",
    "name": "Main Computer DSQC1018",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Main Computer",
    "qty": 1,
    "alternative_pns": [
      "DSQC1018"
    ],
    "primaryImage": "image83.jpeg",
    "docNames": [
      "\u4e3b\u673aDSQC1018"
    ],
    "existing": true,
    "existingImageStatus": "missing",
    "images": [
      "image83.jpeg"
    ]
  },
  {
    "pn": "3HAC058663-001",
    "brand": "ABB",
    "name": "Scalable I/O Digital Base DSQC1030 (16DI/16DO)",
    "cat": "controllers",
    "series": null,
    "equipment_type": "I/O Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC1030"
    ],
    "primaryImage": "image64.jpeg",
    "docNames": [
      "IO\u6a21\u5757DSQC1030"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image64.jpeg"
    ]
  },
  {
    "pn": "3HAC058665-001",
    "brand": "ABB",
    "name": "Scalable I/O Analog Add-on DSQC1032 (4AI/4AO)",
    "cat": "controllers",
    "series": null,
    "equipment_type": "I/O Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC1032"
    ],
    "primaryImage": "image98.jpeg",
    "docNames": [
      "IO\u6a21\u5757DSQC1032"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image98.jpeg"
    ]
  },
  {
    "pn": "DSQC1003",
    "brand": "ABB",
    "name": "Serial Port Board DSQC1003",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Serial Port Board",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image107.jpeg",
    "docNames": [
      "\u4e32\u53e3\u677fDSQC1003"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image107.jpeg",
      "image108.jpeg"
    ]
  },
  {
    "pn": "DSQC1006",
    "brand": "ABB",
    "name": "DeviceNet Board DSQC1006",
    "cat": "controllers",
    "series": null,
    "equipment_type": "DeviceNet Board",
    "qty": 2,
    "alternative_pns": [],
    "primaryImage": "image93.jpeg",
    "docNames": [
      "DeviceNet\u677fDSQC1006 N",
      "DeviceNet\u677fDSQC1006"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image93.jpeg",
      "image94.jpeg"
    ]
  },
  {
    "pn": "DSQC1015",
    "brand": "ABB",
    "name": "Safety Module DSQC1015",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Safety Module",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image63.jpeg",
    "docNames": [
      "\u5b89\u5168\u6a21\u5757DSQC1015"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image63.jpeg"
    ]
  },
  {
    "pn": "DSQC337B",
    "brand": "ABB",
    "name": "Conveyor Tracking Board DSQC337B",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Conveyor Tracking Board",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image54.jpeg",
    "docNames": [
      "\u4f20\u9001\u5e26\u8ddf\u8e2a\u677fDSQC337B"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image54.jpeg"
    ]
  },
  {
    "pn": "DSQC378B",
    "brand": "ABB",
    "name": "CC-Link Board DSQC378B",
    "cat": "controllers",
    "series": null,
    "equipment_type": "CC-Link Board",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image55.jpeg",
    "docNames": [
      "CC-link\u677f\u5361DSQC378B"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image55.jpeg"
    ]
  },
  {
    "pn": "DSQC669",
    "brand": "ABB",
    "name": "EtherNet Board DSQC669",
    "cat": "controllers",
    "series": null,
    "equipment_type": "EtherNet Board",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image80.jpeg",
    "docNames": [
      "EtherNet\u677f\u5361DSQC669"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image80.jpeg",
      "image81.jpeg"
    ]
  },
  {
    "pn": "3HAC028357-001",
    "brand": "ABB",
    "name": "Teach Pendant / FlexPendant DSQC679",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant",
    "qty": 2,
    "alternative_pns": [
      "DSQC679"
    ],
    "primaryImage": "image69.jpeg",
    "docNames": [
      "\u793a\u6559\u5668DSQC679",
      "\u5168\u65b0\u793a\u6559\u5668DSQC679"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image69.jpeg",
      "image88.jpeg",
      "image70.jpeg"
    ]
  },
  {
    "pn": "3HAC033624-001",
    "brand": "ABB",
    "name": "Teach Pendant Mainboard 3HAC033624-001",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant Mainboard",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image99.jpeg",
    "docNames": [
      "\u793a\u6559\u5668\u4e3b\u677f3HAC033624-001"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image99.jpeg",
      "image100.jpeg"
    ]
  },
  {
    "pn": "3HAC052287-002",
    "brand": "ABB",
    "name": "Mode Selector Switch 3HAC052287-002",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Mode Selector Switch",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image96.jpeg",
    "docNames": [
      "\u6863\u4f4d\u5f00\u51733HAC052287-002"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image96.jpeg",
      "image97.jpeg"
    ]
  },
  {
    "pn": "3HNA012283-0001",
    "brand": "ABB",
    "name": "Paint Teach Pendant 3HNA012283-0001",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Paint Teach Pendant",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image104.jpeg",
    "docNames": [
      "\u55b7\u6d82\u793a\u6559\u56683HNA012283-0001"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image104.jpeg",
      "image105.jpeg"
    ]
  },
  {
    "pn": "3HNE00313-1",
    "brand": "ABB",
    "name": "Teach Pendant TPU2 (S4C/S4C+)",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant (legacy)",
    "qty": 1,
    "alternative_pns": [
      "TPU2"
    ],
    "primaryImage": "image89.jpeg",
    "docNames": [
      "\u8001\u6b3e\u793a\u6559\u5668TPU2"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image89.jpeg",
      "image90.jpeg"
    ]
  },
  {
    "pn": "DSQC3060",
    "brand": "ABB",
    "name": "Teach Pendant DSQC3060",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image71.jpeg",
    "docNames": [
      "\u793a\u6559\u5668DSQC3060"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image71.jpeg",
      "image72.jpeg"
    ]
  },
  {
    "pn": "DSQC3122",
    "brand": "ABB",
    "name": "Teach Pendant DSQC3122",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image60.jpeg",
    "docNames": [
      "\u793a\u6559\u5668DSQC3122"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image60.jpeg",
      "image61.jpeg"
    ]
  },
  {
    "pn": "JC200-0049",
    "brand": "ABB",
    "name": "Teach Pendant Joystick JC200-0049",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant Joystick",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image95.jpeg",
    "docNames": [
      "\u5168\u65b0\u793a\u6559\u5668\u6447\u6746JC200-0049"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image95.jpeg"
    ]
  },
  {
    "pn": "3HAC022286-001",
    "brand": "ABB",
    "name": "Serial Measurement Board (SMB) 3HAC022286-001",
    "cat": "motion",
    "series": null,
    "equipment_type": "Serial Measurement Board (SMB)",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image79.jpeg",
    "docNames": [
      "SMB\u677f\u53613HAC022286-001"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image79.jpeg"
    ]
  },
  {
    "pn": "3HAC025338-002",
    "brand": "ABB",
    "name": "Drive Unit 3HAC025338-002",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image59.jpeg",
    "docNames": [
      "ABB\u9a71\u52a83HAC025338-002"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image59.jpeg"
    ]
  },
  {
    "pn": "3HAC025338-004",
    "brand": "ABB",
    "name": "Drive Unit 3HAC025338-004",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image68.jpeg",
    "docNames": [
      "\u9ed1\u9a71\u52a83HAC025338-004"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image68.jpeg"
    ]
  },
  {
    "pn": "3HAC026253-001",
    "brand": "ABB",
    "name": "Power Supply DSQC661 (24VDC/27A)",
    "cat": "motion",
    "series": null,
    "equipment_type": "Power Supply",
    "qty": 1,
    "alternative_pns": [
      "DSQC661"
    ],
    "primaryImage": "image53.jpeg",
    "docNames": [
      "\u7535\u6e90\u6a21\u5757DSQC661"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image53.jpeg"
    ]
  },
  {
    "pn": "3HAC029818-001",
    "brand": "ABB",
    "name": "Drive Unit DSQC663 (6-axis MDU)",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC663"
    ],
    "primaryImage": "image106.jpeg",
    "docNames": [
      "\u9a71\u52a8DSQC663"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image106.jpeg"
    ]
  },
  {
    "pn": "3HAC030923-001",
    "brand": "ABB",
    "name": "External Axis Drive Unit DSQC664 (HV ADU)",
    "cat": "motion",
    "series": null,
    "equipment_type": "External Axis Drive Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC664"
    ],
    "primaryImage": "image56.jpeg",
    "docNames": [
      "\u5916\u90e8\u8f74\u9a71\u52a8DSQC664"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image56.jpeg"
    ]
  },
  {
    "pn": "3HAC035301-001",
    "brand": "ABB",
    "name": "Main Drive Unit LV DSQC406",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC406"
    ],
    "primaryImage": "image91.jpeg",
    "docNames": [
      "\u9a71\u52a8DSQC406"
    ],
    "existing": true,
    "existingImageStatus": "approved",
    "images": [
      "image91.jpeg"
    ]
  },
  {
    "pn": "3HAC044168-001",
    "brand": "ABB",
    "name": "Serial Measurement Board (SMB) 3HAC044168-001",
    "cat": "motion",
    "series": null,
    "equipment_type": "Serial Measurement Board (SMB)",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image84.jpeg",
    "docNames": [
      "SMB\u677f\u53613HAC044168-001"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image84.jpeg"
    ]
  },
  {
    "pn": "3HAC14549-3",
    "brand": "ABB",
    "name": "Drive Unit (compact) 3HAC14549-3",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit (compact)",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image62.jpeg",
    "docNames": [
      "ABB\u5c0f\u9a71\u52a83HAC14549-3"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image62.jpeg"
    ]
  },
  {
    "pn": "3HAC17339-1/01",
    "brand": "ABB",
    "name": "Servo Motor 3HAC17339-1/01",
    "cat": "motion",
    "series": null,
    "equipment_type": "Servo Motor",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image102.jpeg",
    "docNames": [
      "ABB\u7535\u673a3HAC17339-1/01ABB"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image102.jpeg"
    ]
  },
  {
    "pn": "3HAC17340-1/00",
    "brand": "ABB",
    "name": "Servo Motor 3HAC17340-1/00",
    "cat": "motion",
    "series": null,
    "equipment_type": "Servo Motor",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image103.jpeg",
    "docNames": [
      "\u7535\u673a3HAC17340-1/00"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image103.jpeg"
    ]
  },
  {
    "pn": "3HAC17342-1/01",
    "brand": "ABB",
    "name": "Servo Motor 3HAC17342-1/01",
    "cat": "motion",
    "series": null,
    "equipment_type": "Servo Motor",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image101.jpeg",
    "docNames": [
      "ABB\u7535\u673a3HAC17342-1/01"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image101.jpeg"
    ]
  },
  {
    "pn": "3HAC7998-1",
    "brand": "ABB",
    "name": "Encoder Cable 3HAC7998-1",
    "cat": "motion",
    "series": null,
    "equipment_type": "Encoder Cable",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": null,
    "docNames": [
      "\u7f16\u7801\u5668\u7ebf3HAC7998-1"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": []
  },
  {
    "pn": "DSQC431",
    "brand": "ABB",
    "name": "Drive Unit DSQC431",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image82.jpeg",
    "docNames": [
      "\u9a71\u52a8DSQC431"
    ],
    "existing": false,
    "existingImageStatus": null,
    "images": [
      "image82.jpeg"
    ]
  }
];
