// AUTO-GENERATED by scripts/build-real-inventory.ts from the supplier document.
// Real ABB inventory (robots + parts) that nodibot actually stocks. Reviewed by a
// human before import. Regenerate only when the source document changes.
//
// Summary: 65 unique items (24 robots, 41 parts);
// 17 already existed as crawled rows, 48 are new.

export type RealCat = "robots" | "controllers" | "hmi" | "motion" | "mechanical" | "consumables";

export interface RealItem {
  pn: string;                    // canonical part number (unique)
  brand: "ABB";
  name: string;                  // English display name
  cat: RealCat;
  series: string | null;
  equipment_type: string | null;
  qty: number;                   // physical units in hand
  alternative_pns: string[];
  primaryImage: string | null;   // media filename inside the source docx
  docNames: string[];            // original doc line names (traceability)
  existing: boolean;             // already a row in the DB (was crawled/dummy)
  existingImageStatus: string | null;
}

export const REAL_ITEMS: RealItem[] = [
  {
    "pn": "IRB120-3/0.6",
    "brand": "ABB",
    "name": "IRB 120 — 3 kg / 0.6 m",
    "cat": "robots",
    "series": "IRB 120",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image35.jpeg",
    "docNames": [
      "IRB120-3/0.6"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB1200-5/0.9",
    "brand": "ABB",
    "name": "IRB 1200 — 5 kg / 0.9 m",
    "cat": "robots",
    "series": "IRB 1200",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image5.jpeg",
    "docNames": [
      "IRB1200-5/0.9"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB1200-7/0.7",
    "brand": "ABB",
    "name": "IRB 1200 — 7 kg / 0.7 m",
    "cat": "robots",
    "series": "IRB 1200",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image3.jpeg",
    "docNames": [
      "IRB1200-7/0.7"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB14000-0.5/0.5",
    "brand": "ABB",
    "name": "IRB 14000 — 0.5 kg / 0.5 m (YuMi)",
    "cat": "robots",
    "series": "IRB 14000",
    "equipment_type": "dual-arm collaborative robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image49.jpeg",
    "docNames": [
      "IRB14000-0.5/0.5"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB1410-5/1.45",
    "brand": "ABB",
    "name": "IRB 1410 — 5 kg / 1.45 m",
    "cat": "robots",
    "series": "IRB 1410",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image31.jpeg",
    "docNames": [
      "IRB1410-5/1.45"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB1600-10/1.45",
    "brand": "ABB",
    "name": "IRB 1600 — 10 kg / 1.45 m",
    "cat": "robots",
    "series": "IRB 1600",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image15.jpeg",
    "docNames": [
      "IRB1600-10/1.45"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB1600ID-6/1.55",
    "brand": "ABB",
    "name": "IRB 1600ID — 6 kg / 1.55 m",
    "cat": "robots",
    "series": "IRB 1600ID",
    "equipment_type": "6-axis articulated robot (integrated dressing)",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image7.jpeg",
    "docNames": [
      "IRB1600ID-6/1.55"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB2400/16",
    "brand": "ABB",
    "name": "IRB 2400/16",
    "cat": "robots",
    "series": "IRB 2400",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image39.jpeg",
    "docNames": [
      "IRB2400/16"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB2600-12/1.85",
    "brand": "ABB",
    "name": "IRB 2600 — 12 kg / 1.85 m",
    "cat": "robots",
    "series": "IRB 2600",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image37.jpeg",
    "docNames": [
      "IRB2600-12/1.85"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB2600-20/1.65",
    "brand": "ABB",
    "name": "IRB 2600 — 20 kg / 1.65 m",
    "cat": "robots",
    "series": "IRB 2600",
    "equipment_type": "6-axis articulated robot",
    "qty": 2,
    "alternative_pns": [],
    "primaryImage": "image1.jpeg",
    "docNames": [
      "IRB2600-20/1.65",
      "IRB2600-20/1.65"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB2600ID/8/2.00",
    "brand": "ABB",
    "name": "IRB 2600ID — 8 kg / 2.00 m",
    "cat": "robots",
    "series": "IRB 2600ID",
    "equipment_type": "6-axis articulated robot (integrated dressing)",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image51.jpeg",
    "docNames": [
      "IRB2600ID/8/2.00"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB4400/60",
    "brand": "ABB",
    "name": "IRB 4400/60",
    "cat": "robots",
    "series": "IRB 4400",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image29.jpeg",
    "docNames": [
      "IRB4400/60"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB4400L-10",
    "brand": "ABB",
    "name": "IRB 4400L",
    "cat": "robots",
    "series": "IRB 4400L",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image41.jpeg",
    "docNames": [
      "IRB4400L-10"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB4600-40/2.55",
    "brand": "ABB",
    "name": "IRB 4600 — 40 kg / 2.55 m",
    "cat": "robots",
    "series": "IRB 4600",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image1.jpeg",
    "docNames": [
      "IRB4600-40/2.55"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB4600-45/2.05",
    "brand": "ABB",
    "name": "IRB 4600 — 45 kg / 2.05 m",
    "cat": "robots",
    "series": "IRB 4600",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image45.jpeg",
    "docNames": [
      "IRB4600-45/2.05"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB4600-60/2.05",
    "brand": "ABB",
    "name": "IRB 4600 — 60 kg / 2.05 m",
    "cat": "robots",
    "series": "IRB 4600",
    "equipment_type": "6-axis articulated robot",
    "qty": 2,
    "alternative_pns": [],
    "primaryImage": "image17.jpeg",
    "docNames": [
      "IRB4600-60/2.05",
      "IRB4600-60/2.05"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB52",
    "brand": "ABB",
    "name": "IRB 52 Paint Robot",
    "cat": "robots",
    "series": "IRB 52",
    "equipment_type": "paint robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image43.jpeg",
    "docNames": [
      "IRB52"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB5510",
    "brand": "ABB",
    "name": "IRB 5510 Paint Robot",
    "cat": "robots",
    "series": "IRB 5510",
    "equipment_type": "paint robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image25.jpeg",
    "docNames": [
      "IRB5510"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB660-180/3.15",
    "brand": "ABB",
    "name": "IRB 660 — 180 kg / 3.15 m Palletizer",
    "cat": "robots",
    "series": "IRB 660",
    "equipment_type": "4-axis palletizing robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image13.jpeg",
    "docNames": [
      "IRB660-180/3.15"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB6640-130/3.2",
    "brand": "ABB",
    "name": "IRB 6640 — 130 kg / 3.2 m",
    "cat": "robots",
    "series": "IRB 6640",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image33.jpeg",
    "docNames": [
      "IRB6640-130/3.2"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB6700-150/3.2",
    "brand": "ABB",
    "name": "IRB 6700 — 150 kg / 3.2 m",
    "cat": "robots",
    "series": "IRB 6700",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image27.jpeg",
    "docNames": [
      "IRB6700-150/3.2"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB6700-200/2.60",
    "brand": "ABB",
    "name": "IRB 6700 — 200 kg / 2.60 m",
    "cat": "robots",
    "series": "IRB 6700",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image9.jpeg",
    "docNames": [
      "IRB6700-200/2.60"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB6700-235/2.65",
    "brand": "ABB",
    "name": "IRB 6700 — 235 kg / 2.65 m",
    "cat": "robots",
    "series": "IRB 6700",
    "equipment_type": "6-axis articulated robot",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image21.jpeg",
    "docNames": [
      "IRB6700-235/2.65"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "IRB6700-300/2.70",
    "brand": "ABB",
    "name": "IRB 6700 — 300 kg / 2.70 m",
    "cat": "robots",
    "series": "IRB 6700",
    "equipment_type": "6-axis articulated robot",
    "qty": 2,
    "alternative_pns": [],
    "primaryImage": "image23.jpeg",
    "docNames": [
      "IRB6700-300/2.70",
      "IRB6700-300/2.70"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC044075-001",
    "brand": "ABB",
    "name": "SMB Battery 7.2V (Li-SOCl2)",
    "cat": "consumables",
    "series": null,
    "equipment_type": "Battery",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image92.jpeg",
    "docNames": [
      "ABB电池3HAC044075-001"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC16831-1",
    "brand": "ABB",
    "name": "Battery 3HAC16831-1",
    "cat": "consumables",
    "series": null,
    "equipment_type": "Battery",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image87.jpeg",
    "docNames": [
      "ABB电池3HAC16831-1"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC025097-001",
    "brand": "ABB",
    "name": "Main Computer DSQC639",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Main Computer",
    "qty": 2,
    "alternative_pns": [
      "DSQC639"
    ],
    "primaryImage": "image67.jpeg",
    "docNames": [
      "主机3HAC025097-001",
      "主板DSQC639"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC025784-001",
    "brand": "ABB",
    "name": "Combi I/O Unit DSQC651 (8DI/8DO/2AO)",
    "cat": "controllers",
    "series": null,
    "equipment_type": "I/O Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC651"
    ],
    "primaryImage": "image65.jpeg",
    "docNames": [
      "IO模块DSQC651"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC025917-001",
    "brand": "ABB",
    "name": "I/O Unit DSQC652 (16DI/16DO)",
    "cat": "controllers",
    "series": null,
    "equipment_type": "I/O Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC652"
    ],
    "primaryImage": "image66.jpeg",
    "docNames": [
      "IO模块DSQC652"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC026272-001",
    "brand": "ABB",
    "name": "Safety Board 3HAC026272-001",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Safety Board",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image76.jpeg",
    "docNames": [
      "安全板卡3HAC026272-001"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC029157-001",
    "brand": "ABB",
    "name": "Axis Computer DSQC668",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Axis Computer",
    "qty": 2,
    "alternative_pns": [
      "DSQC668"
    ],
    "primaryImage": "image77.jpeg",
    "docNames": [
      "轴计算机板卡DSQC668",
      "轴计算机板卡DSQC668"
    ],
    "existing": true,
    "existingImageStatus": "missing"
  },
  {
    "pn": "3HAC031670-001",
    "brand": "ABB",
    "name": "ProfiNet Board DSQC688",
    "cat": "controllers",
    "series": null,
    "equipment_type": "ProfiNet Board",
    "qty": 1,
    "alternative_pns": [
      "DSQC688"
    ],
    "primaryImage": "image73.jpeg",
    "docNames": [
      "Profinet板卡DSQC688"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC037084-001",
    "brand": "ABB",
    "name": "DeviceNet Board DSQC697 (SST-DN4-PCI)",
    "cat": "controllers",
    "series": null,
    "equipment_type": "DeviceNet Board",
    "qty": 1,
    "alternative_pns": [
      "DSQC697"
    ],
    "primaryImage": "image57.jpeg",
    "docNames": [
      "DeviceNet板DSQC697"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC042766-001",
    "brand": "ABB",
    "name": "Main Computer DSQC1000",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Main Computer",
    "qty": 1,
    "alternative_pns": [
      "DSQC1000"
    ],
    "primaryImage": "image75.jpeg",
    "docNames": [
      "ABB主机DSQC1000"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC050363-001",
    "brand": "ABB",
    "name": "Main Computer DSQC1018",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Main Computer",
    "qty": 1,
    "alternative_pns": [
      "DSQC1018"
    ],
    "primaryImage": "image83.jpeg",
    "docNames": [
      "主机DSQC1018"
    ],
    "existing": true,
    "existingImageStatus": "missing"
  },
  {
    "pn": "3HAC058663-001",
    "brand": "ABB",
    "name": "Scalable I/O Digital Base DSQC1030 (16DI/16DO)",
    "cat": "controllers",
    "series": null,
    "equipment_type": "I/O Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC1030"
    ],
    "primaryImage": "image64.jpeg",
    "docNames": [
      "IO模块DSQC1030"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC058665-001",
    "brand": "ABB",
    "name": "Scalable I/O Analog Add-on DSQC1032 (4AI/4AO)",
    "cat": "controllers",
    "series": null,
    "equipment_type": "I/O Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC1032"
    ],
    "primaryImage": "image98.jpeg",
    "docNames": [
      "IO模块DSQC1032"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "DSQC1003",
    "brand": "ABB",
    "name": "Serial Port Board DSQC1003",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Serial Port Board",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image107.jpeg",
    "docNames": [
      "串口板DSQC1003"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "DSQC1006",
    "brand": "ABB",
    "name": "DeviceNet Board DSQC1006",
    "cat": "controllers",
    "series": null,
    "equipment_type": "DeviceNet Board",
    "qty": 2,
    "alternative_pns": [],
    "primaryImage": "image93.jpeg",
    "docNames": [
      "DeviceNet板DSQC1006 N",
      "DeviceNet板DSQC1006"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "DSQC1015",
    "brand": "ABB",
    "name": "Safety Module DSQC1015",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Safety Module",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image63.jpeg",
    "docNames": [
      "安全模块DSQC1015"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "DSQC337B",
    "brand": "ABB",
    "name": "Conveyor Tracking Board DSQC337B",
    "cat": "controllers",
    "series": null,
    "equipment_type": "Conveyor Tracking Board",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image54.jpeg",
    "docNames": [
      "传送带跟踪板DSQC337B"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "DSQC378B",
    "brand": "ABB",
    "name": "CC-Link Board DSQC378B",
    "cat": "controllers",
    "series": null,
    "equipment_type": "CC-Link Board",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image55.jpeg",
    "docNames": [
      "CC-link板卡DSQC378B"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "DSQC669",
    "brand": "ABB",
    "name": "EtherNet Board DSQC669",
    "cat": "controllers",
    "series": null,
    "equipment_type": "EtherNet Board",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image80.jpeg",
    "docNames": [
      "EtherNet板卡DSQC669"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC028357-001",
    "brand": "ABB",
    "name": "Teach Pendant / FlexPendant DSQC679",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant",
    "qty": 2,
    "alternative_pns": [
      "DSQC679"
    ],
    "primaryImage": "image69.jpeg",
    "docNames": [
      "示教器DSQC679",
      "全新示教器DSQC679"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC033624-001",
    "brand": "ABB",
    "name": "Teach Pendant Mainboard 3HAC033624-001",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant Mainboard",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image99.jpeg",
    "docNames": [
      "示教器主板3HAC033624-001"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC052287-002",
    "brand": "ABB",
    "name": "Mode Selector Switch 3HAC052287-002",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Mode Selector Switch",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image96.jpeg",
    "docNames": [
      "档位开关3HAC052287-002"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HNA012283-0001",
    "brand": "ABB",
    "name": "Paint Teach Pendant 3HNA012283-0001",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Paint Teach Pendant",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image104.jpeg",
    "docNames": [
      "喷涂示教器3HNA012283-0001"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HNE00313-1",
    "brand": "ABB",
    "name": "Teach Pendant TPU2 (S4C/S4C+)",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant (legacy)",
    "qty": 1,
    "alternative_pns": [
      "TPU2"
    ],
    "primaryImage": "image89.jpeg",
    "docNames": [
      "老款示教器TPU2"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "DSQC3060",
    "brand": "ABB",
    "name": "Teach Pendant DSQC3060",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image71.jpeg",
    "docNames": [
      "示教器DSQC3060"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "DSQC3122",
    "brand": "ABB",
    "name": "Teach Pendant DSQC3122",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image60.jpeg",
    "docNames": [
      "示教器DSQC3122"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "JC200-0049",
    "brand": "ABB",
    "name": "Teach Pendant Joystick JC200-0049",
    "cat": "hmi",
    "series": null,
    "equipment_type": "Teach Pendant Joystick",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image95.jpeg",
    "docNames": [
      "全新示教器摇杆JC200-0049"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC022286-001",
    "brand": "ABB",
    "name": "Serial Measurement Board (SMB) 3HAC022286-001",
    "cat": "motion",
    "series": null,
    "equipment_type": "Serial Measurement Board (SMB)",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image79.jpeg",
    "docNames": [
      "SMB板卡3HAC022286-001"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC025338-002",
    "brand": "ABB",
    "name": "Drive Unit 3HAC025338-002",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image59.jpeg",
    "docNames": [
      "ABB驱动3HAC025338-002"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC025338-004",
    "brand": "ABB",
    "name": "Drive Unit 3HAC025338-004",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image68.jpeg",
    "docNames": [
      "黑驱动3HAC025338-004"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC026253-001",
    "brand": "ABB",
    "name": "Power Supply DSQC661 (24VDC/27A)",
    "cat": "motion",
    "series": null,
    "equipment_type": "Power Supply",
    "qty": 1,
    "alternative_pns": [
      "DSQC661"
    ],
    "primaryImage": "image53.jpeg",
    "docNames": [
      "电源模块DSQC661"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC029818-001",
    "brand": "ABB",
    "name": "Drive Unit DSQC663 (6-axis MDU)",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC663"
    ],
    "primaryImage": "image106.jpeg",
    "docNames": [
      "驱动DSQC663"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC030923-001",
    "brand": "ABB",
    "name": "External Axis Drive Unit DSQC664 (HV ADU)",
    "cat": "motion",
    "series": null,
    "equipment_type": "External Axis Drive Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC664"
    ],
    "primaryImage": "image56.jpeg",
    "docNames": [
      "外部轴驱动DSQC664"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC035301-001",
    "brand": "ABB",
    "name": "Main Drive Unit LV DSQC406",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit",
    "qty": 1,
    "alternative_pns": [
      "DSQC406"
    ],
    "primaryImage": "image91.jpeg",
    "docNames": [
      "驱动DSQC406"
    ],
    "existing": true,
    "existingImageStatus": "approved"
  },
  {
    "pn": "3HAC044168-001",
    "brand": "ABB",
    "name": "Serial Measurement Board (SMB) 3HAC044168-001",
    "cat": "motion",
    "series": null,
    "equipment_type": "Serial Measurement Board (SMB)",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image84.jpeg",
    "docNames": [
      "SMB板卡3HAC044168-001"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC14549-3",
    "brand": "ABB",
    "name": "Drive Unit (compact) 3HAC14549-3",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit (compact)",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image62.jpeg",
    "docNames": [
      "ABB小驱动3HAC14549-3"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC17339-1/01",
    "brand": "ABB",
    "name": "Servo Motor 3HAC17339-1/01",
    "cat": "motion",
    "series": null,
    "equipment_type": "Servo Motor",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image102.jpeg",
    "docNames": [
      "ABB电机3HAC17339-1/01ABB"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC17340-1/00",
    "brand": "ABB",
    "name": "Servo Motor 3HAC17340-1/00",
    "cat": "motion",
    "series": null,
    "equipment_type": "Servo Motor",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image103.jpeg",
    "docNames": [
      "电机3HAC17340-1/00"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC17342-1/01",
    "brand": "ABB",
    "name": "Servo Motor 3HAC17342-1/01",
    "cat": "motion",
    "series": null,
    "equipment_type": "Servo Motor",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image101.jpeg",
    "docNames": [
      "ABB电机3HAC17342-1/01"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "3HAC7998-1",
    "brand": "ABB",
    "name": "Encoder Cable 3HAC7998-1",
    "cat": "motion",
    "series": null,
    "equipment_type": "Encoder Cable",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": null,
    "docNames": [
      "编码器线3HAC7998-1"
    ],
    "existing": false,
    "existingImageStatus": null
  },
  {
    "pn": "DSQC431",
    "brand": "ABB",
    "name": "Drive Unit DSQC431",
    "cat": "motion",
    "series": null,
    "equipment_type": "Drive Unit",
    "qty": 1,
    "alternative_pns": [],
    "primaryImage": "image82.jpeg",
    "docNames": [
      "驱动DSQC431"
    ],
    "existing": false,
    "existingImageStatus": null
  }
];
